#!/usr/bin/env python3
"""
V2: Prepare sentiment analysis payloads from v2 filtered CSV.

This version reads hn_ai_filtered_v2.csv which has already been generated by
fetch_and_filter_ai_posts_v2.py with the proper schema including parent_text.

Generates Stage 1 payloads (aspect detection) - one payload per comment/subcomment row.

Input CSV Schema (v2):
- comment_id, comment_type, story_id, story_title, story_by, comment_time,
  comment_text, comment_by, parent_id, parent_text, ai_score, match_info

Output JSONL Schema:
{
  "payload_id": "payload_000042",
  "payload_type": "direct_comment" | "nested_comment",
  "story_id": "12345",
  "story_title": "...",
  "comment_id": "67890",
  "comment_text": "...",
  "parent_comment_id": "..." (optional),
  "parent_comment_text": "..." (optional),
  "stage1_messages": [...]
}
"""

import argparse
import csv
import json
from pathlib import Path

# STAGE 1: Aspect Detection System Prompt
STAGE1_SYSTEM_PROMPT = """You are an aspect detection system for AI-related Hacker News discussions.

Your task: Identify which aspects are mentioned in the text. For each aspect:
1. present: true/false (is it explicitly or implicitly mentioned?)
2. evidence: exact text span or brief summary showing where it appears
3. confidence: 0.0 to 1.0 (how certain are you?)

ASPECT TAXONOMY (6 aspects):
- coding_speed: code generation speed, execution time, latency, inference speed, time to completion
- coding_performance: code quality, correctness, accuracy, reliability, consistency, best practices
- cost_price: pricing models, compute costs, API fees, ROI, affordability, efficiency
- ethics: bias, fairness, transparency, accountability, AI alignment, moral implications
- innovation: novelty, breakthroughs, technical advancement, research impact, SOTA, capabilities
- skepticism_hype: doubt about claims, overhype criticism, feasibility concerns, reality checks, limitations

RULES:
- Only mark present=true if the aspect is ACTUALLY discussed (not tangentially related)
- Provide exact text span as evidence when possible
- If multiple aspects apply, detect ALL of them
- If NO aspects are relevant, return empty aspects array: {"aspects": []}
- Be strict: don't hallucinate aspects that aren't there

Respond with valid JSON only:
{
  "aspects": [
    {
      "aspect": "coding_speed",
      "present": true,
      "evidence": "runs 10x faster than GPT-4",
      "confidence": 0.95
    }
  ]
}"""


def create_stage1_messages(story_title: str, comment_text: str, parent_text: str = "") -> tuple:
    """
    Create Stage 1 (aspect detection) messages.
    
    Args:
        story_title: Story title text
        comment_text: Comment text
        parent_text: Optional parent comment text (for nested comments)
    
    Returns:
        Tuple of (payload_type, messages_array)
    """
    if parent_text and parent_text.strip():
        # Nested comment with parent context
        user_content = f"""Story: {story_title}

Parent comment: {parent_text}

Reply: {comment_text}

Detect which aspects are mentioned in this reply about the AI story above."""
        payload_type = "nested_comment"
    else:
        # Direct comment (no parent)
        user_content = f"""Story: {story_title}

Comment: {comment_text}

Detect which aspects are mentioned in this comment about the AI story above."""
        payload_type = "direct_comment"
    
    return payload_type, [
        {"role": "system", "content": STAGE1_SYSTEM_PROMPT},
        {"role": "user", "content": user_content}
    ]


def prepare_payloads_v2(
    input_csv: Path,
    output_jsonl: Path,
    max_payloads: int = 0
):
    """
    Generate sentiment analysis payloads from v2 filtered CSV.
    
    Each row becomes one payload (direct_comment or nested_comment based on parent_text).
    
    Args:
        input_csv: Path to hn_ai_filtered_v2.csv
        output_jsonl: Path to output JSONL file
        max_payloads: Maximum payloads to generate (0 = unlimited)
    """
    
    print(f"Reading v2 filtered CSV from {input_csv}...")
    
    payload_count = 0
    direct_count = 0
    nested_count = 0
    skipped_count = 0
    
    with open(input_csv, "r", encoding="utf-8") as infile, \
         open(output_jsonl, "w", encoding="utf-8") as outfile:
        
        reader = csv.DictReader(infile)
        
        for row in reader:
            if max_payloads > 0 and payload_count >= max_payloads:
                break
            
            comment_id = row["comment_id"]
            comment_text = row.get("comment_text", "").strip()
            
            # Skip empty comments
            if not comment_text:
                skipped_count += 1
                continue
            
            story_id = row["story_id"]
            story_title = row["story_title"]
            parent_id = row.get("parent_id", "").strip()
            parent_text = row.get("parent_text", "").strip()
            
            payload_id = f"payload_{payload_count:06d}"
            
            # Create messages (determines payload type based on parent_text)
            payload_type, stage1_messages = create_stage1_messages(
                story_title=story_title,
                comment_text=comment_text,
                parent_text=parent_text
            )
            
            payload = {
                "payload_id": payload_id,
                "payload_type": payload_type,
                "story_id": story_id,
                "story_title": story_title,
                "comment_id": comment_id,
                "comment_text": comment_text,
                "stage1_messages": stage1_messages,
                "ai_score": int(row.get("ai_score", 0)),
                "match_info": row.get("match_info", "")
            }
            
            # Add parent fields if present
            if parent_id:
                payload["parent_comment_id"] = parent_id
            if parent_text:
                payload["parent_comment_text"] = parent_text
            
            outfile.write(json.dumps(payload) + "\n")
            
            payload_count += 1
            if payload_type == "nested_comment":
                nested_count += 1
            else:
                direct_count += 1
            
            if payload_count % 1000 == 0:
                print(f"  Generated {payload_count:,} payloads...")
    
    # Summary
    print(f"\n{'='*70}")
    print(f"V2 PAYLOAD GENERATION SUMMARY:")
    print(f"  Direct comments:    {direct_count:>10,}")
    print(f"  Nested comments:    {nested_count:>10,}")
    print(f"  {'─'*48}")
    print(f"  Total payloads:     {payload_count:>10,}")
    print(f"  Skipped (empty):    {skipped_count:>10,}")
    print(f"  Output: {output_jsonl}")
    print(f"{'='*70}")


def main():
    parser = argparse.ArgumentParser(
        description="Prepare v2 sentiment analysis payloads from hn_ai_filtered_v2.csv",
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("hn_ai_filtered_v2.csv"),
        help="Input v2 filtered CSV (default: hn_ai_filtered_v2.csv)"
    )
    
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("sentiment_payloads_v2.jsonl"),
        help="Output JSONL path (default: sentiment_payloads_v2.jsonl)"
    )
    
    parser.add_argument(
        "--max-payloads",
        type=int,
        default=0,
        help="Maximum payloads to generate (0 = unlimited, default: 0)"
    )
    
    args = parser.parse_args()
    
    if not args.input.is_file():
        print(f"ERROR: Input file does not exist: {args.input}")
        print(f"Run fetch_and_filter_ai_posts_v2.py first to generate the filtered CSV.")
        return
    
    prepare_payloads_v2(
        input_csv=args.input,
        output_jsonl=args.output,
        max_payloads=args.max_payloads
    )
    
    print(f"\nV2 payloads saved to: {args.output}")


if __name__ == "__main__":
    main()
