#!/usr/bin/env python3
"""
V2: UNIFIED sentiment analysis runner - TWO-STAGE COMPLETE PIPELINE

Works with v2 payloads generated by prepare_sentiment_payloads_v2.py

PIPELINE:
  Stage 1: Aspect Detection (input: sentiment_payloads_v2.jsonl)
  ↓
  Stage 2 Prep: Filter by confidence, generate stage2_messages
  ↓
  Stage 2: Aspect Sentiment Classification
  ↓
  Merge: Combine results into final output

    stage2_success = 0
    stage2_error = 0
    
    with open(stage2_input, "r", encoding="utf-8") as infile, \
         open(stage2_output, "w", encoding="utf-8") as outfile:
        batch2: List[Dict[str, Any]] = []
        idx = 0
        for line in infile:
            if not line.strip():
                continue
            try:
                payload = json.loads(line)
            except json.JSONDecodeError:
                continue
            batch2.append(payload)
            if len(batch2) >= batch_size:
                messages = build_stage2_batch_messages(batch2)
                start_time = time.time()
                result = call_innkube(messages, model, api_key, timeout)
                elapsed = time.time() - start_time
                if result["error"]:
                    for item in batch2:
                        idx += 1
                        stage2_error += 1
                        output_record = {
                            "payload_id": item["payload_id"],
                            "payload_type": item.get("payload_type"),
                            "story_id": item.get("story_id"),
                            "model": model,
                            "detected_aspects": item.get("detected_aspects", []),
                            "stage2_result": None,
                            "stage1_elapsed": item.get("stage1_elapsed", 0),
                            "stage2_elapsed": round(elapsed, 2),
                            "error": result["error"],
                        }
                        outfile.write(json.dumps(output_record) + "\n")
                        print(f"[Stage2 {idx}] {output_record['payload_id']}: ❌ ERROR (batch)")
                else:
                    try:
                        responses = result["response"]
                        if not isinstance(responses, list):
                            raise ValueError("Stage2 batch response is not a list")
                        if len(responses) != len(batch2):
                            raise ValueError(f"Stage2 batch length mismatch: expected {len(batch2)}, got {len(responses)}")
                        for item, resp in zip(batch2, responses):
                            idx += 1
                            output_record = {
                                "payload_id": item["payload_id"],
                                "payload_type": item.get("payload_type"),
                                "story_id": item.get("story_id"),
                                "model": model,
                                "detected_aspects": item.get("detected_aspects", []),
                                "stage2_result": resp,
                                "stage1_elapsed": item.get("stage1_elapsed", 0),
                                "stage2_elapsed": round(elapsed, 2),
                                "error": None,
                            }
                            outfile.write(json.dumps(output_record) + "\n")
                            stage2_success += 1
                            print(f"[Stage2 {idx}] {output_record['payload_id']}: ✅ ({elapsed:.1f}s batch)")
                    except Exception as e:
                        for item in batch2:
                            idx += 1
                            stage2_error += 1
                            output_record = {
                                "payload_id": item["payload_id"],
                                "payload_type": item.get("payload_type"),
                                "story_id": item.get("story_id"),
                                "model": model,
                                "detected_aspects": item.get("detected_aspects", []),
                                "stage2_result": None,
                                "stage1_elapsed": item.get("stage1_elapsed", 0),
                                "stage2_elapsed": round(elapsed, 2),
                                "error": f"Batch parse error: {e}",
                            }
                            outfile.write(json.dumps(output_record) + "\n")
                            print(f"[Stage2 {idx}] {output_record['payload_id']}: ❌ PARSE ERROR (batch)")
                outfile.flush()
                batch2 = []
        if batch2:
            messages = build_stage2_batch_messages(batch2)
            start_time = time.time()
            result = call_innkube(messages, model, api_key, timeout)
            elapsed = time.time() - start_time
            if result["error"]:
                for item in batch2:
                    idx += 1
                    stage2_error += 1
                    output_record = {
                        "payload_id": item["payload_id"],
                        "payload_type": item.get("payload_type"),
                        "story_id": item.get("story_id"),
                        "model": model,
                        "detected_aspects": item.get("detected_aspects", []),
                        "stage2_result": None,
                        "stage1_elapsed": item.get("stage1_elapsed", 0),
                        "stage2_elapsed": round(elapsed, 2),
                        "error": result["error"],
                    }
                    outfile.write(json.dumps(output_record) + "\n")
                    print(f"[Stage2 {idx}] {output_record['payload_id']}: ❌ ERROR (batch)")
            else:
                try:
                    responses = result["response"]
                    if not isinstance(responses, list):
                        raise ValueError("Stage2 batch response is not a list")
                    if len(responses) != len(batch2):
                        raise ValueError(f"Stage2 batch length mismatch: expected {len(batch2)}, got {len(responses)}")
                    for item, resp in zip(batch2, responses):
                        idx += 1
                        output_record = {
                            "payload_id": item["payload_id"],
                            "payload_type": item.get("payload_type"),
                            "story_id": item.get("story_id"),
                            "model": model,
                            "detected_aspects": item.get("detected_aspects", []),
                            "stage2_result": resp,
                            "stage1_elapsed": item.get("stage1_elapsed", 0),
                            "stage2_elapsed": round(elapsed, 2),
                            "error": None,
                        }
                        outfile.write(json.dumps(output_record) + "\n")
                        stage2_success += 1
                        print(f"[Stage2 {idx}] {output_record['payload_id']}: ✅ ({elapsed:.1f}s batch)")
                except Exception as e:
                    for item in batch2:
                        idx += 1
                        stage2_error += 1
                        output_record = {
                            "payload_id": item["payload_id"],
                            "payload_type": item.get("payload_type"),
                            "story_id": item.get("story_id"),
                            "model": model,
                            "detected_aspects": item.get("detected_aspects", []),
                            "stage2_result": None,
                            "stage1_elapsed": item.get("stage1_elapsed", 0),
                            "stage2_elapsed": round(elapsed, 2),
                            "error": f"Batch parse error: {e}",
                        }
                        outfile.write(json.dumps(output_record) + "\n")
                        print(f"[Stage2 {idx}] {output_record['payload_id']}: ❌ PARSE ERROR (batch)")
            outfile.flush()
  ]
}"""


def normalize_aspects(aspects: Any) -> List[Dict[str, Any]]:
    """Normalize LLM Stage 1 'aspects' output to a list of dicts.

    Accepts various shapes: list of dicts, list of strings, dict mapping.
    Ensures each item has keys: aspect(str), present(bool), evidence(str), confidence(float).
    """
    normalized: List[Dict[str, Any]] = []
    if not aspects:
        return normalized

    # If dict mapping {aspect_name: true/false}
    if isinstance(aspects, dict):
        for k, v in aspects.items():
            try:
                present = bool(v)
            except Exception:
                present = True
            normalized.append({
                "aspect": str(k),
                "present": present,
                "evidence": "",
                "confidence": 0.7 if present else 0.5,
            })
        return normalized

    # If list-like
    if isinstance(aspects, list):
        for item in aspects:
            if isinstance(item, dict):
                aspect_name = item.get("aspect") or item.get("name") or item.get("type")
                if not aspect_name and len(item) == 1:
                    # Single-key dict like {"ethics": true}
                    k = next(iter(item.keys()))
                    v = item[k]
                    normalized.append({
                        "aspect": str(k),
                        "present": bool(v),
                        "evidence": item.get("evidence", ""),
                        "confidence": float(item.get("confidence", 0.7)),
                    })
                    continue
                normalized.append({
                    "aspect": str(aspect_name) if aspect_name is not None else "unknown",
                    "present": bool(item.get("present", True)),
                    "evidence": item.get("evidence", ""),
                    "confidence": float(item.get("confidence", 0.7)),
                })
            elif isinstance(item, str):
                # Plain string aspect name
                normalized.append({
                    "aspect": item,
                    "present": True,
                    "evidence": "",
                    "confidence": 0.7,
                })
            else:
                # Unknown type; skip
                continue
        return normalized

    # Fallback: unknown shape
    return normalized


def load_api_key(key_path: Path) -> str:
    """Load API key from file."""
    with open(key_path, "r", encoding="utf-8") as f:
        return f.read().strip()


def call_innkube(
    messages: list,
    model: str,
    api_key: str,
    timeout: int = DEFAULT_TIMEOUT
) -> Dict[str, Any]:
    """Call InnKube chat completions endpoint."""
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json"
    }
    
    payload = {
        "model": model,
        "messages": messages,
        "temperature": 0.3
    }
    
    try:
        resp = requests.post(
            INNKUBE_URL,
            headers=headers,
            json=payload,
            timeout=timeout
        )
        resp.raise_for_status()
        
        data = resp.json()
        content = data["choices"][0]["message"]["content"]
        
        try:
            parsed = json.loads(content)
            return {"response": parsed, "error": None}
        except json.JSONDecodeError as e:
            return {
                "response": None,
                "error": f"JSON decode error: {e}. Raw: {content[:200]}"
            }
    
    except requests.exceptions.Timeout:
        return {"response": None, "error": f"Request timeout after {timeout}s"}
    except requests.exceptions.RequestException as e:
        return {"response": None, "error": f"Request error: {e}"}
    except Exception as e:
        return {"response": None, "error": f"Unexpected error: {e}"}


def build_stage1_batch_messages(batch: List[Dict[str, Any]]) -> List[Dict[str, str]]:
    """Construct a single Stage 1 request for a batch of payloads."""
    instructions = [
        "You are an aspect detection system for AI-related Hacker News discussions.",
        "Process ALL items in this batch and return a JSON ARRAY of length EXACTLY N (one per item, SAME ORDER).",
        "Each element must be: { 'payload_id': str, 'aspects': [ {aspect, present, evidence, confidence} ] }.",
        "If no aspects for an item, use an empty array. JSON ONLY. No markdown, no prose, no explanations.",
        "Do not invent payloads. Do not drop payloads. The array length MUST equal N.",
    ]
    user_blocks = []
    for idx, item in enumerate(batch):
        user_blocks.append(
            f"Item {idx+1} | payload_id={item.get('payload_id','unknown')}\n"
            f"Story: {item.get('story_title','')}\n"
            f"Comment: {item.get('comment_text','')}\n"
            f"Parent: {item.get('parent_text','')}"
        )
    return [
        {"role": "system", "content": "\n".join(instructions)},
        {"role": "user", "content": "\n\n".join(user_blocks)},
    ]


def build_stage2_batch_messages(batch: List[Dict[str, Any]]) -> List[Dict[str, str]]:
    """Construct a single Stage 2 request for a batch of payloads."""
    instructions = [
        "You are an expert AI sentiment analyst.",
        "Process ALL items and respond with a JSON ARRAY of length EXACTLY N in the SAME ORDER as provided.",
        "Each element: { 'payload_id': str, 'aspect_sentiments': [ {aspect, sentiment, score, confidence, reasoning} ] }.",
        "Sentiment ∈ {positive, neutral, negative, mixed}; score -1.0..1.0; confidence 0.0..1.0; concise reasoning; JSON ONLY.",
        "Do not invent payloads. Do not drop payloads. The array length MUST equal N.",
    ]
    user_blocks = []
    for idx, item in enumerate(batch):
        aspects_text = "\n".join([
            f"- {a.get('aspect','unknown')}: {a.get('evidence','No evidence')} (conf={a.get('confidence',0)})"
            for a in item.get("detected_aspects", [])
        ])
        user_blocks.append(
            f"Item {idx+1} | payload_id={item.get('payload_id','unknown')}\n"
            f"Comment: {item.get('comment_text','')}\n"
            f"Detected aspects:\n{aspects_text}"
        )
    return [
        {"role": "system", "content": "\n".join(instructions)},
        {"role": "user", "content": "\n\n".join(user_blocks)},
    ]


def load_processed_payload_ids(output_path: Path) -> set:
    """Load already processed payload IDs from output JSONL."""
    processed = set()
    if not output_path.exists():
        return processed
    
    with open(output_path, "r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                try:
                    result = json.loads(line)
                    processed.add(result["payload_id"])
                except (json.JSONDecodeError, KeyError):
                    continue
    
    return processed


def run_unified_pipeline(
    input_jsonl: Path,
    output_jsonl: Path,
    model: str,
    api_key: str,
    timeout: int,
    max_payloads: int = 0,
    sleep_seconds: float = 0.0,
    min_confidence: float = DEFAULT_MIN_CONFIDENCE,
    resume: bool = True,
    concurrency: int = 1,
    batch_size: int = DEFAULT_BATCH_SIZE
):
    """
    Run complete TWO-STAGE pipeline:
    Stage 1 → Stage 2 Prep → Stage 2 → Merge
    """
    
    # Stage 1 temporary files
    stage1_output = Path("stage1_temp_v2.jsonl")
    stage2_input = Path("stage2_payloads_temp_v2.jsonl")
    stage2_output = Path("stage2_temp_v2.jsonl")
    
    print(f"\n{'='*70}")
    print(f"V2 UNIFIED TWO-STAGE PIPELINE")
    print(f"{'='*70}")
    print(f"Input: {input_jsonl}")
    print(f"Output: {output_jsonl}")
    print(f"Model: {model}")
    print(f"Batch size: {batch_size} (single LLM call per batch)")
    print(f"Min Confidence (Stage 2 filter): {min_confidence}")
    print(f"{'='*70}\n")
    
    # =====================================================================
    # STAGE 1: ASPECT DETECTION
    # =====================================================================
    print("STAGE 1: Running aspect detection (batched)...\n")
    
    processed_ids = set()
    if resume and stage1_output.exists():
        processed_ids = load_processed_payload_ids(stage1_output)
        if processed_ids:
            print(f"Resume: Found {len(processed_ids):,} Stage 1 results\n")
    
    stage1_mode = "a" if resume else "w"
    stage1_count = 0
    stage1_success = 0
    stage1_error = 0
    
    with open(input_jsonl, "r", encoding="utf-8") as infile, \
         open(stage1_output, stage1_mode, encoding="utf-8") as outfile:
        batch: List[Dict[str, Any]] = []
        for line in infile:
            if not line.strip():
                continue
            try:
                payload = json.loads(line)
            except json.JSONDecodeError:
                continue
            payload_id = payload.get("payload_id", f"unknown_{stage1_count}")
            if payload_id in processed_ids:
                continue
            if max_payloads > 0 and stage1_count >= max_payloads:
                break
            batch.append(payload)
            if len(batch) >= batch_size:
                messages = build_stage1_batch_messages(batch)
                start_time = time.time()
                result = call_innkube(messages, model, api_key, timeout)
                elapsed = time.time() - start_time
                if result["error"]:
                    for item in batch:
                        stage1_count += 1
                        stage1_error += 1
                        record = {
                            "payload_id": item.get("payload_id"),
                            "payload_type": item.get("payload_type"),
                            "story_id": item.get("story_id"),
                            "comment_text": item.get("comment_text", ""),
                            "model": model,
                            "stage1_result": None,
                            "stage1_elapsed": round(elapsed, 2),
                            "error": result["error"],
                        }
                        outfile.write(json.dumps(record) + "\n")
                        print(f"[Stage1 {stage1_count}] {record['payload_id']}: ❌ ERROR (batch)")
                else:
                    try:
                        responses = result["response"]
                        if not isinstance(responses, list):
                            raise ValueError("Stage1 batch response is not a list")
                        if len(responses) != len(batch):
                            raise ValueError(f"Stage1 batch length mismatch: expected {len(batch)}, got {len(responses)}")
                        for item, resp in zip(batch, responses):
                            stage1_count += 1
                            record = {
                                "payload_id": item.get("payload_id"),
                                "payload_type": item.get("payload_type"),
                                "story_id": item.get("story_id"),
                                "comment_text": item.get("comment_text", ""),
                                "model": model,
                                "stage1_result": resp,
                                "stage1_elapsed": round(elapsed, 2),
                                "error": None,
                            }
                            outfile.write(json.dumps(record) + "\n")
                            aspects = normalize_aspects(resp.get("aspects")) if isinstance(resp, dict) else []
                            stage1_success += 1
                            print(f"[Stage1 {stage1_count}] {record['payload_id']}: ✅ {len(aspects)} aspects ({elapsed:.1f}s batch)")
                    except Exception as e:
                        for item in batch:
                            stage1_count += 1
                            stage1_error += 1
                            record = {
                                "payload_id": item.get("payload_id"),
                                "payload_type": item.get("payload_type"),
                                "story_id": item.get("story_id"),
                                "comment_text": item.get("comment_text", ""),
                                "model": model,
                                "stage1_result": None,
                                "stage1_elapsed": round(elapsed, 2),
                                "error": f"Batch parse error: {e}",
                            }
                            outfile.write(json.dumps(record) + "\n")
                            print(f"[Stage1 {stage1_count}] {record['payload_id']}: ❌ PARSE ERROR (batch)")
                outfile.flush()
                batch = []
        if batch:
            messages = build_stage1_batch_messages(batch)
            start_time = time.time()
            result = call_innkube(messages, model, api_key, timeout)
            elapsed = time.time() - start_time
            if result["error"]:
                for item in batch:
                    stage1_count += 1
                    stage1_error += 1
                    record = {
                        "payload_id": item.get("payload_id"),
                        "payload_type": item.get("payload_type"),
                        "story_id": item.get("story_id"),
                        "comment_text": item.get("comment_text", ""),
                        "model": model,
                        "stage1_result": None,
                        "stage1_elapsed": round(elapsed, 2),
                        "error": result["error"],
                    }
                    outfile.write(json.dumps(record) + "\n")
                    print(f"[Stage1 {stage1_count}] {record['payload_id']}: ❌ ERROR (batch)")
            else:
                try:
                    responses = result["response"]
                    if not isinstance(responses, list):
                        raise ValueError("Stage1 batch response is not a list")
                    if len(responses) != len(batch):
                        raise ValueError(f"Stage1 batch length mismatch: expected {len(batch)}, got {len(responses)}")
                    for item, resp in zip(batch, responses):
                        stage1_count += 1
                        record = {
                            "payload_id": item.get("payload_id"),
                            "payload_type": item.get("payload_type"),
                            "story_id": item.get("story_id"),
                            "comment_text": item.get("comment_text", ""),
                            "model": model,
                            "stage1_result": resp,
                            "stage1_elapsed": round(elapsed, 2),
                            "error": None,
                        }
                        outfile.write(json.dumps(record) + "\n")
                        aspects = normalize_aspects(resp.get("aspects")) if isinstance(resp, dict) else []
                        stage1_success += 1
                        print(f"[Stage1 {stage1_count}] {record['payload_id']}: ✅ {len(aspects)} aspects ({elapsed:.1f}s batch)")
                except Exception as e:
                    for item in batch:
                        stage1_count += 1
                        stage1_error += 1
                        record = {
                            "payload_id": item.get("payload_id"),
                            "payload_type": item.get("payload_type"),
                            "story_id": item.get("story_id"),
                            "comment_text": item.get("comment_text", ""),
                            "model": model,
                            "stage1_result": None,
                            "stage1_elapsed": round(elapsed, 2),
                            "error": f"Batch parse error: {e}",
                        }
                        outfile.write(json.dumps(record) + "\n")
                        print(f"[Stage1 {stage1_count}] {record['payload_id']}: ❌ PARSE ERROR (batch)")
            outfile.flush()
            if sleep_seconds > 0:
                time.sleep(sleep_seconds)
    
    print(f"\nStage 1 complete: {stage1_success} success, {stage1_error} errors\n")
    
    # =====================================================================
    # STAGE 2 PREP: FILTER & GENERATE STAGE 2 PAYLOADS
    # =====================================================================
    print("STAGE 2 PREP: Filtering by confidence & generating payloads...\n")
    
    stage2_count = 0
    stage2_qualified = 0
    
    with open(stage1_output, "r", encoding="utf-8") as infile, \
         open(stage2_input, "w", encoding="utf-8") as outfile:
        
        for line in infile:
            if not line.strip():
                continue
            
            try:
                record = json.loads(line)
            except json.JSONDecodeError:
                continue
            
            stage1_result = record.get("stage1_result", {})
            if not stage1_result:
                continue
            
            aspects = stage1_result.get("aspects", [])
            aspects = normalize_aspects(aspects)
            if not aspects:
                stage2_count += 1
                print(f"[S2Prep {stage2_count}] {record['payload_id']}: No aspects detected, skip Stage 2")
                continue
            
            # Filter by confidence
            qualified_aspects = [
                a for a in aspects 
                if float(a.get("confidence", 0)) >= min_confidence and a.get("present", True)
            ]
            
            if not qualified_aspects:
                stage2_count += 1
                print(f"[S2Prep {stage2_count}] {record['payload_id']}: No aspects above confidence {min_confidence}, skip Stage 2")
                continue
            
            # Generate Stage 2 messages
            stage2_messages = create_stage2_messages(
                record.get("comment_text", ""),
                qualified_aspects
            )
            
            stage2_payload = {
                "payload_id": record["payload_id"],
                "payload_type": record.get("payload_type"),
                "story_id": record.get("story_id"),
                "comment_text": record.get("comment_text", ""),
                "detected_aspects": qualified_aspects,
                "stage2_messages": stage2_messages,
                "stage1_elapsed": record.get("stage1_elapsed", 0)
            }
            
            outfile.write(json.dumps(stage2_payload) + "\n")
            
            stage2_count += 1
            stage2_qualified += 1
            aspect_names = [a["aspect"] for a in qualified_aspects[:2]]
            print(f"[S2Prep {stage2_count}] {record['payload_id']}: ✅ {len(qualified_aspects)} aspects → Stage 2 ({', '.join(aspect_names)}...)")
    
    reduction_pct = 100 * (1 - stage2_qualified / max(1, stage2_count))
    print(f"\nStage 2 Prep complete: {stage2_qualified}/{stage2_count} qualified ({reduction_pct:.0f}% filtered)\n")
    
    # =====================================================================
    # STAGE 2: ASPECT SENTIMENT CLASSIFICATION
    # =====================================================================
    print("STAGE 2: Running aspect sentiment classification...\n")
    
    stage2_success = 0
    stage2_error = 0
    
    def stage2_worker(payload: Dict[str, Any]) -> Dict[str, Any]:
        payload_id = payload["payload_id"]
        stage2_messages = payload.get("stage2_messages", [])
        detected_aspects = payload.get("detected_aspects", [])
        start_time = time.time()
        result = call_innkube(stage2_messages, model, api_key, timeout)
        stage2_elapsed = time.time() - start_time
        return {
            "payload_id": payload_id,
            "payload_type": payload.get("payload_type"),
            "story_id": payload.get("story_id"),
            "model": model,
            "detected_aspects": detected_aspects,
            "stage2_result": result["response"],
            "stage1_elapsed": payload.get("stage1_elapsed", 0),
            "stage2_elapsed": round(stage2_elapsed, 2),
            "error": result["error"]
        }

    with open(stage2_input, "r", encoding="utf-8") as infile, \
         open(stage2_output, "w", encoding="utf-8") as outfile:
        batch2: List[Dict[str, Any]] = []
        idx = 0
        for line in infile:
            if not line.strip():
                continue
            try:
                payload = json.loads(line)
            except json.JSONDecodeError:
                continue
            batch2.append(payload)
            if len(batch2) >= concurrency:
                with concurrent.futures.ThreadPoolExecutor(max_workers=concurrency) as executor:
                    for output_record in executor.map(stage2_worker, batch2):
                        idx += 1
                        outfile.write(json.dumps(output_record) + "\n")
                        outfile.flush()
                        if output_record["error"]:
                            stage2_error += 1
                            print(f"[Stage2 {idx}] {output_record['payload_id']}: ❌ ERROR")
                        else:
                            stage2_success += 1
                            print(f"[Stage2 {idx}] {output_record['payload_id']}: ✅ ({output_record['stage2_elapsed']:.1f}s)")
                        if sleep_seconds > 0:
                            time.sleep(sleep_seconds)
                batch2 = []
        if batch2:
            with concurrent.futures.ThreadPoolExecutor(max_workers=concurrency) as executor:
                for output_record in executor.map(stage2_worker, batch2):
                    idx += 1
                    outfile.write(json.dumps(output_record) + "\n")
                    outfile.flush()
                    if output_record["error"]:
                        stage2_error += 1
                        print(f"[Stage2 {idx}] {output_record['payload_id']}: ❌ ERROR")
                    else:
                        stage2_success += 1
                        print(f"[Stage2 {idx}] {output_record['payload_id']}: ✅ ({output_record['stage2_elapsed']:.1f}s)")
                    if sleep_seconds > 0:
                        time.sleep(sleep_seconds)
    
    print(f"\nStage 2 complete: {stage2_success} success, {stage2_error} errors\n")
    
    # =====================================================================
    # MERGE: COMBINE STAGE 1 + STAGE 2 RESULTS
    # =====================================================================
    print("MERGE: Combining Stage 1 + Stage 2 results...\n")
    
    # Load Stage 2 results
    stage2_data = {}
    with open(stage2_output, "r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                try:
                    record = json.loads(line)
                    stage2_data[record["payload_id"]] = record
                except (json.JSONDecodeError, KeyError):
                    continue
    
    merge_count = 0
    
    # Merge Stage 1 + Stage 2
    with open(stage1_output, "r", encoding="utf-8") as infile, \
         open(output_jsonl, "w", encoding="utf-8") as outfile:
        
        for line in infile:
            if not line.strip():
                continue
            
            try:
                stage1_record = json.loads(line)
            except json.JSONDecodeError:
                continue
            
            payload_id = stage1_record["payload_id"]
            stage1_result = stage1_record.get("stage1_result")
            
            # Handle None or missing stage1_result
            if stage1_result is None:
                detected_aspects = []
            else:
                detected_aspects = stage1_result.get("aspects", [])
            
            # Check if this payload went to Stage 2
            if payload_id in stage2_data:
                stage2_record = stage2_data[payload_id]
                stage2_result = stage2_record.get("stage2_result", {})
                aspect_sentiments = stage2_result.get("aspect_sentiments", [])
                
                # Calculate overall sentiment from aspect sentiments
                if aspect_sentiments:
                    scores = [a.get("score", 0) for a in aspect_sentiments]
                    avg_score = sum(scores) / len(scores)
                    if avg_score > 0.3:
                        overall_sentiment = "positive"
                    elif avg_score < -0.3:
                        overall_sentiment = "negative"
                    else:
                        overall_sentiment = "neutral"
                else:
                    aspect_sentiments = []
                    overall_sentiment = "neutral"
                    avg_score = 0.0
                
                total_elapsed = stage1_record.get("stage1_elapsed", 0) + stage2_record.get("stage2_elapsed", 0)
            else:
                # No Stage 2 (below confidence threshold)
                aspect_sentiments = []
                overall_sentiment = "neutral"
                avg_score = 0.0
                total_elapsed = stage1_record.get("stage1_elapsed", 0)
            
            final_record = {
                "payload_id": payload_id,
                "payload_type": stage1_record.get("payload_type"),
                "story_id": stage1_record.get("story_id"),
                "model": stage1_record.get("model", model),
                "detected_aspects": detected_aspects,
                "aspect_sentiments": aspect_sentiments,
                "overall_sentiment": overall_sentiment,
                "overall_score": round(avg_score, 2),
                "stage1_elapsed": stage1_record.get("stage1_elapsed", 0),
                "stage2_elapsed": stage2_data.get(payload_id, {}).get("stage2_elapsed", 0),
                "total_elapsed": round(total_elapsed, 2),
                "error": stage1_record.get("error")
            }
            
            outfile.write(json.dumps(final_record) + "\n")
            merge_count += 1
    
    print(f"Merge complete: {merge_count} records written to {output_jsonl}\n")
    
    # Cleanup temporary files
    for temp_file in [stage1_output, stage2_input, stage2_output]:
        if temp_file.exists():
            temp_file.unlink()
    
    print(f"{'='*70}")
    print(f"V2 PIPELINE COMPLETE")
    print(f"  Stage 1: {stage1_success} success, {stage1_error} errors")
    print(f"  Stage 2: {stage2_qualified} qualified, {stage2_success} success, {stage2_error} errors")
    print(f"  Final Output: {output_jsonl}")
    print(f"{'='*70}\n")


def main():
    parser = argparse.ArgumentParser(
        description="V2 unified two-stage sentiment analysis pipeline",
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("sentiment_payloads_v2.jsonl"),
        help="Input JSONL with stage1_messages (default: sentiment_payloads_v2.jsonl)"
    )
    
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("final_sentiment_results_v2.jsonl"),
        help="Output JSONL for final results (default: final_sentiment_results_v2.jsonl)"
    )
    
    parser.add_argument(
        "--model",
        type=str,
        default=DEFAULT_MODEL,
        choices=ALLOWED_MODELS,
        help=f"Model to use (default: {DEFAULT_MODEL})"
    )
    
    parser.add_argument(
        "--api-key-path",
        type=Path,
        default=Path("key"),
        help="Path to API key file (default: key)"
    )
    
    parser.add_argument(
        "--timeout",
        type=int,
        default=DEFAULT_TIMEOUT,
        help=f"Request timeout in seconds (default: {DEFAULT_TIMEOUT})"
    )
    
    parser.add_argument(
        "--max-payloads",
        type=int,
        default=0,
        help="Maximum payloads to process (0 = unlimited, default: 0)"
    )
    
    parser.add_argument(
        "--sleep",
        type=float,
        default=0.0,
        help="Sleep seconds between requests (default: 0.0)"
    )
    
    parser.add_argument(
        "--min-confidence",
        type=float,
        default=DEFAULT_MIN_CONFIDENCE,
        help=f"Minimum confidence for Stage 2 filtering (default: {DEFAULT_MIN_CONFIDENCE})"
    )
    
    parser.add_argument(
        "--no-resume",
        action="store_true",
        help="Disable resume mode"
    )
    parser.add_argument(
        "--concurrency",
        type=int,
        default=1,
        help="Deprecated: kept for compatibility; batching sends batch-size items per request"
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=DEFAULT_BATCH_SIZE,
        help="How many payloads to send per LLM request (default: 10)"
    )
    
    args = parser.parse_args()
    
    if not args.input.is_file():
        print(f"ERROR: Input file does not exist: {args.input}")
        return
    
    if not args.api_key_path.is_file():
        print(f"ERROR: API key file does not exist: {args.api_key_path}")
        return
    
    api_key = load_api_key(args.api_key_path)
    
    run_unified_pipeline(
        input_jsonl=args.input,
        output_jsonl=args.output,
        model=args.model,
        api_key=api_key,
        timeout=args.timeout,
        max_payloads=args.max_payloads,
        sleep_seconds=args.sleep,
        min_confidence=args.min_confidence,
        resume=not args.no_resume,
        concurrency=max(1, args.concurrency),
        batch_size=max(1, args.batch_size)
    )
    
    print(f"\nResults saved to: {args.output}")


if __name__ == "__main__":
    main()
